language: python
python:
- '2.7'
install:
- pip install -r requirements-dev.txt
- pip install coveralls
script:
- coverage run --source=vpc_subnet_calculator -m unittest discover
- flake8 --exclude .git,*.pyc,env --ignore F403,F405
after_success:
- coveralls
